print ("Content-type:text/html\r\n\r\n")
print ('<html>')
print ('<head>')
print ('<title>Hello Word - First MYSERVER Program</title>')
print ('</head>')
print ('<body>')
print ('<h2>Hello Word! This is my first MYSERVER program</h2>')
print ('</body>')
print ('</html>')