create table ACCOUNT (
	Account_id SERIAL NOT NULL PRIMARY KEY,
	User_id VARCHAR(50) NOT NULL UNIQUE, 
	Password VARCHAR(50) NOT NULL,
	First_name VARCHAR(50) NOT NULL,
	Last_name VARCHAR(50) NOT NULL,
	Phone_number CHAR(11) NOT NULL,
	Birthday DATE,
	Sex VARCHAR(7),
	Address VARCHAR(100),
	Job VARCHAR(50), 
	Membership_status VARCHAR(10),
	Is_admin boolean DEFAULT false
);

insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('tthow0@newsvine.com', 'P1kpyhNvV', 'Tabbie', 'Thow', '01034468473',  '2006-12-04', 'Male', null, null, 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('bbrellin1@abc.net.au', 'XYdVk0cgAj', 'Blake', 'Brellin', '01059645765', null, null, null, null, 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('ecoatsworth2@patch.com', 'XUMWxiCYoJ', 'Errol', 'Coatsworth', '01024068008', '2009-11-30', 'Male', '837 Novick Road', 'Programmer Analyst IV', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('sbrumwell3@blogger.com', 'eZx8CJqUVtr', 'Sibelle', 'Brumwell', '01042024776',  '2002-12-14','Female', null, null, 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('tshermar4@booking.com', 'Nd1EMqXkHnG2', 'Taddeo', 'Shermar', '01002787331', '1966-12-01', 'Male', '3072 Upham Hill', 'Automation Specialist IV', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('sscutts5@blog.com', '4blsqNds', 'See', 'Scutts', '01090813531', null, null, null, null, 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('jlinkin6@rambler.ru', 'ETDlJ7Uo3dj', 'Jacky', 'Linkin', '01012270748', '2011-10-14', 'Male', '8 Dakota Junction', 'Software Test Engineer II', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('jbeltzner7@ebay.com', 'Ygd8jjGcb7', 'Joyce', 'Beltzner', '01006004498',  '1965-11-16','Female', null, null, 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('sgummory8@weather.com', 'VsieDCZWH3', 'Stephanie', 'Gummory', '01067128172', '2014-07-19','Male', null, null, 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('ebarron9@shareasale.com', 'K9wMuIP', 'Eartha', 'Barron', '01025365249', '1964-03-02', 'Female', '9 Annamark Place', 'Chief Design Engineer', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('zgreenroyda@usgs.gov', 'Xe3N86p', 'Zebulen', 'Greenroyd', '01008124499', '1956-11-25','Female', null, null, 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('klefriecb@princeton.edu', 'bUDk0auQ2q', 'Kipp', 'Le Friec', '01092257033', '1945-03-09', 'Male', '09 Warner Hill', 'Senior Cost Accountant', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('celvenc@scientificamerican.com', '2OGgd5UWJbJ', 'Chaddie', 'Elven', '01026033897', null, null, null, null, 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('nvossgend@intel.com', 'vnEEuGKL', 'Nalani', 'Vossgen', '01017020867', '1952-06-04', 'Female', '3747 North Alley', 'Administrative Assistant IV', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('rmartinse@deviantart.com', 'vp7xzecIZ', 'Randee', 'Martins', '01061191163', '1981-11-06', 'Female', null, null, 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('qbayfordf@fc2.com', '2XHzfVGej', 'Quent', 'Bayford', '01037833616', '1934-07-13', 'Male', '4 Chive Street', 'Account Executive', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('rtomalag@wiley.com', 'k8cvU5lxPuEs', 'Rodrick', 'Tomala', '01026904295',  '1991-11-06', 'Female', null, null, 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('lguilaemh@europa.eu', 'TZZiYd5', 'Lynn', 'Guilaem', '01053591239', null, null, null, null, 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('swatersi@devhub.com', 'fz3Sm0E', 'Sophi', 'Waters', '01055252669', '2018-12-19', 'Female', '643 Hoepker Road', 'Recruiter', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('jfiremanj@studiopress.com', 'QxfR7MiV7THJ', 'Joshuah', 'Fireman', '01051407533', '1942-06-09', 'Male', '1997 Mosinee Way', 'Structural Engineer', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('ddimmickk@nytimes.com', 'zRG9cH4C7l', 'Dave', 'Dimmick', '01075553001',  '1963-07-13','Male', null, null, 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('lstolbergerl@ihg.com', '1yBlIxv', 'Laverna', 'Stolberger', '01063716945', '2003-01-12', 'Female', '00 Schiller Terrace', 'Engineer II', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('maldcornem@drupal.org', 'QC6kgMTkiMw', 'Marguerite', 'Aldcorne', '01047485457', '1951-02-19', 'Female', '1633 Arrowood Junction', 'Staff Accountant IV', 'Basic', true);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('btindlen@spiegel.de', 'lkg4h7ftmG', 'Brittne', 'Tindle', '01006687765', '2013-10-28', 'Female', '20 Thierer Trail', 'Recruiting Manager', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('lgoldingayo@craigslist.org', 'ZwOgrQBAe658', 'Lil', 'Goldingay', '01034178556', null, null, null, null, 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('cboveyp@biglobe.ne.jp', 'sJb7Deijsc', 'Coop', 'Bovey', '01038084055', '2000-09-20', 'Male', '14 Anthes Avenue', 'Marketing Manager', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('gburberyeq@cloudflare.com', 'AiqQ93NQtL', 'Granny', 'Burberye', '01044172498',  '1984-05-12', 'Male', null, null, 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('cizatsonr@unicef.org', 'nPmHHQqW', 'Clayborne', 'Izatson', '01078352368',  '1967-02-08', 'Male', null, null, 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('vgilmans@ocn.ne.jp', 'ir9SNah5zf', 'Valentijn', 'Gilman', '01048957840', '1998-04-01','Male', null, null, 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('spattlet@guardian.co.uk', 'sAceKM3ttQCw', 'Shandee', 'Pattle', '01010802322', '1944-06-09', 'Female', '57 John Wall Trail', 'Cost Accountant', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('chayeru@si.edu', 'yo5nCURvZI', 'Carlos', 'Hayer', '01014246797', '1965-03-19','Male', null, null, 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('csangarv@feedburner.com', '6v5Wtl', 'Cristiano', 'Sangar', '01064057380', '1987-11-28', 'Male', '9295 Doe Crossing Avenue', 'Safety Technician IV', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('tprynnew@hp.com', 'zqfVP4MKx0', 'Tootsie', 'Prynne', '01066717127',  '1987-09-18','Male', null, null, 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('epallesenx@deliciousdays.com', 'Tl8TUYh3o', 'Ernest', 'Pallesen', '01063224988', '2004-11-17', 'Male', '49602 Ryan Trail', 'Senior Quality Engineer', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('tmcurey@tmall.com', 'K7isB0pD', 'Thomasin', 'McUre', '01075844351', null, null, null, null, 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('cmackillz@paginegialle.it', 'TXUVTbYSQJ', 'Connor', 'MacKill', '01006580618', '1975-09-27', 'Male', '67910 Elgar Avenue', 'Research Nurse', 'Basic', true);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('treeson10@miitbeian.gov.cn', 'gpX9wp', 'Toinette', 'Reeson', '01084935324',  '1988-01-17','Male', null, null, 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('atranfield11@fastcompany.com', 'rJ0EQMBh9', 'Angel', 'Tranfield', '01042823190', '1990-06-02', 'Male', '23413 Moulton Trail', 'Registered Nurse', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('eskirven12@jiathis.com', 'S9euV0brAPue', 'Eugene', 'Skirven', '01092937129', '1944-12-26', 'Male', '3 Dwight Crossing', 'Data Coordiator', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('lbeltzner13@livejournal.com', 'iqlpWZpLsm0', 'Lorie', 'Beltzner', '01068134627', '1971-09-30', 'Female', '56 Springview Plaza', 'Geological Engineer', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('mblodgetts14@usatoday.com', 'iZtfgde', 'Marcille', 'Blodgetts', '01051824170', '1946-05-02', 'Female', '48208 Fairview Street', 'Editor', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('mbage15@about.com', '8K1yIioDS', 'Maurise', 'Bage', '01061947015', '1969-02-23', 'Male', '5 Ronald Regan Junction', 'Structural Engineer', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('wassard16@infoseek.co.jp', 'UJkWwVYxUOa', 'Waldon', 'Assard', '01050568472', '1936-11-03', 'Male', '60 Sunfield Drive', 'Senior Financial Analyst', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('aperacco17@php.net', 'ntFvbyVjZ', 'Alexio', 'Peracco', '01052348611',  '2018-08-15','Male', null, null, 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('sbrayshaw18@businessinsider.com', 'NENHkhz', 'Sarah', 'Brayshaw', '01085283543', null, null, null, null, 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('awringe19@google.com.br', 'SeTGOc', 'Ardyce', 'Wringe', '01097276159',  '2018-12-27','Female', null, null, 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('mkennerley1a@tripadvisor.com', 'BRafKN', 'Malvina', 'Kennerley', '01007674956', '1930-04-10', 'Female', '34 Spohn Hill', 'Associate Professor', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('ywhitrod1b@archive.org', 'oB1b5FxNT1', 'Yuri', 'Whitrod', '01094994202', '2001-04-02', 'Male', null, null, 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('mpiborn1c@networkadvertising.org', 'ssTUZL8', 'Merl', 'Piborn', '01046365533', '1951-06-18', 'Female', '6 Mandrake Circle', 'Staff Accountant II', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('blobbe1d@youtube.com', 'ZAs3DYdjjDlg', 'Braden', 'Lobbe', '01002457602', '2020-03-04', 'Male', '592 Chinook Pass', 'VP Accounting', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('tcrowther1e@nyu.edu', 'fLhjRdHm', 'Tracey', 'Crowther', '01046747332', null, null, null, null, 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('slabusquiere1f@flavors.me', 'dz7kZlyA9', 'Sheri', 'Labusquiere', '01071073647', '2005-04-04', 'Female', '3 Dorton Point', 'Structural Analysis Engineer', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('ytowndrow1g@ebay.com', 'uUC977', 'Yul', 'Towndrow', '01042517488', '1970-01-11','Male', null, null, 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('cmarshman1h@state.tx.us', 'DPVGkLa0tH', 'Cosmo', 'Marshman', '01012539610', '2006-02-26', 'Male', '64884 Bowman Trail', 'Food Chemist', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('nmisk1i@boston.com', 'SAJ5Lg', 'Nicky', 'Misk', '01043907046', '1947-05-29', 'Female', '9 Macpherson Pass', 'VP Marketing', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('ljacquot1j@ezinearticles.com', '06ZFp2asFki', 'Lorri', 'Jacquot', '01042189290', '1996-10-10', 'Female', '689 Elmside Road', 'Senior Developer', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('hluthwood1k@rambler.ru', 'h18Hmk51', 'Harriett', 'Luthwood', '01028238086',  '1984-02-21','Male', null, null, 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('nenderby1l@histats.com', '51xJKk3mB', 'Nanni', 'Enderby', '01083306548', '1930-06-27', 'Female', '8 Rieder Place', 'Structural Analysis Engineer', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('bfrankling1m@trellian.com', 'r8t5oFw4PLXL', 'Bancroft', 'Frankling', '01054991846', '1965-05-25', 'Male', '716 1st Alley', 'Information Systems Manager', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('brollin1n@prnewswire.com', 'FMBMeLo', 'Barbe', 'Rollin', '01091222789', null, null, null, null, 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('uatherley1o@cocolog-nifty.com', '5ClXvw3pPO6', 'Ulrick', 'Atherley', '01096742894', '2011-07-13', 'Male', '9000 Loftsgordon Place', 'Librarian', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('cisselee1p@360.cn', 'Xh7BMG4', 'Cristionna', 'Isselee', '01034208024', null, null, null, null, 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('fgrimsditch1q@photobucket.com', 'ehfBTs', 'Fawne', 'Grimsditch', '01063940528', '2013-04-10', 'Female', '968 Forest Crossing', 'Speech Pathologist', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('oplait1r@addtoany.com', 'pK7DHAI8C', 'Ole', 'Plait', '01066293966', null, null, null, null, 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('lovershott1s@dailymotion.com', '56WCAclUwD', 'Lani', 'Overshott', '01092299905', '1939-08-01', 'Female', '1181 Esker Lane', 'Web Developer I', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('vausting1t@usa.gov', 'vJ7acZd8bTQ', 'Vikki', 'Austing', '01027988975', '1931-01-26', 'Female', '4007 Mendota Circle', 'VP Quality Control', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('blocke1u@hostgator.com', 'QQEQxo', 'Birch', 'Locke', '01018248773', '1935-06-16', 'Male', '87 Schurz Avenue', 'Junior Executive', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('rcutten1v@google.it', '3uLLqH4HTw7m', 'Reilly', 'Cutten', '01058390340', '1956-04-28', 'Male', '8458 Transport Crossing', 'Engineer II', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('akanwell1w@nyu.edu', 'NZrQFx', 'Adele', 'Kanwell', '01022528384', '1988-12-30', 'Female', '09213 Shopko Pass', 'VP Product Management', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('dburroughes1x@bbc.co.uk', 'X6H84lLtQfMN', 'Dorree', 'Burroughes', '01087754991', '1975-11-18', 'Female', '937 Lunder Junction', 'General Manager', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('gbaston1y@ovh.net', 'YYEnN7CT2aOC', 'Guntar', 'Baston', '01032168049', '1985-05-17', 'Male', '9 Continental Plaza', 'Assistant Professor', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('jjira1z@godaddy.com', 'tJiQenkXyV', 'Jolynn', 'Jira', '01035634026', '1992-02-26', 'Female', '132 Linden Trail', 'VP Accounting', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('jscouller20@marriott.com', 'G8VsOkl7LkQZ', 'Jorge', 'Scouller', '01027796779', null, null, null, null, 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('rwhitwood21@pagesperso-orange.fr', 'Y8TWDaE6qkzL', 'Rey', 'Whitwood', '01049814334', '1987-09-16', 'Male', '4812 Anzinger Point', 'General Manager', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('mlozano22@si.edu', 'xVOiyOKBO', 'Marijn', 'Lozano', '01012693062', '2003-07-15', 'Male', '469 Knutson Trail', 'Associate Professor', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('rgerler23@nyu.edu', 'aLwuCE6tNQ1Y', 'Rodolphe', 'Gerler', '01026262685', null, null, null, null, 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('pmatula24@devhub.com', 'sUA71CXYMB', 'Padraic', 'Matula', '01097916273', null, null, null, null, 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('abreckenridge25@bbb.org', 'fUZyWY', 'Augustina', 'Breckenridge', '01024027650', '1982-09-13', 'Female', '89660 Green Pass', 'Sales Representative', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('adecourcey26@gravatar.com', 'BxWeQrv7s', 'Averill', 'de Courcey', '01081537941', '1963-04-30', 'Male', '863 Fair Oaks Alley', 'Research Associate', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('vbassindale27@thetimes.co.uk', 'rlVW3nw9', 'Vida', 'Bassindale', '01061611998', '1930-12-27', 'Female', '95 Forest Run Point', 'Graphic Designer', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('jburde28@liveinternet.ru', '9jh0fTX', 'Julie', 'Burde', '01096143338', '2013-08-31', 'Male', '0 Hoard Terrace', 'Pharmacist', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('aborsay29@slashdot.org', '5cXI7q9', 'Arlan', 'Borsay', '01000012947', '1969-12-18', 'Male', '64 Springview Center', 'Data Coordiator', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('mdeandisie2a@1und1.de', '3XNZD7Xs', 'Marshall', 'De Andisie', '01054881840', '2004-05-15', 'Male', '958 Nancy Avenue', 'Sales Associate', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('fhoulton2b@ustream.tv', 'NmzC2b', 'Freddie', 'Houlton', '01010214090', '1999-03-18', 'Female', '72419 Brickson Park Road', 'Assistant Manager', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('vcrockett2c@deliciousdays.com', '2adgPIS0A6M', 'Vidovik', 'Crockett', '01004923259', '2017-02-28', 'Male', '39307 Randy Hill', 'Senior Quality Engineer', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('bbehrendsen2d@drupal.org', 'QXm8HQEDtMU', 'Bink', 'Behrendsen', '01076861745', '1991-01-16', 'Male', '8 Bultman Road', 'GIS Technical Architect', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('bcully2e@pen.io', 'aZkwz5LYDqM7', 'Broderick', 'Cully', '01005897661', '1982-10-27', 'Male', '4563 Everett Junction', 'Paralegal', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('crogger2f@bloglovin.com', 'XqrYbl78J', 'Clementius', 'Rogger', '01000938988',  '1961-03-14','Female', null, null, 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('hbaythrop2g@joomla.org', 'EJPwlxCp', 'Hersh', 'Baythrop', '01023407801', '2015-07-10','Female', null, null, 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('nflaws2h@so-net.ne.jp', '8FAzEy1t', 'Neil', 'Flaws', '01060142791', '1999-10-07', 'Male', '14970 Arizona Pass', 'Geological Engineer', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('tlarret2i@over-blog.com', 'vBcFWc', 'Tad', 'Larret', '01092383968', '2008-05-23', 'Male', '63610 Clarendon Place', 'Quality Control Specialist', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('psonghurst2j@omniture.com', 'unUMUqpSAoU', 'Patty', 'Songhurst', '01049419663',  '1954-04-15','Female', null, null, 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('shammor2k@jigsy.com', 'uAxAAp4HTPPe', 'Sancho', 'Hammor', '01018299594', '2020-06-06', 'Male', '1 Maryland Drive', 'Analog Circuit Design manager', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('rsmee2l@yahoo.co.jp', 'iWE98R04Epfy', 'Regan', 'Smee', '01068377056', '2005-09-29', 'Female', '9327 Novick Terrace', 'Civil Engineer', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('vhaug2m@scientificamerican.com', 'D4QasD2eiJp', 'Verna', 'Haug', '01091793021', '2001-08-02', 'Female', '81499 1st Alley', 'Legal Assistant', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('lwornham2n@webmd.com', 'xtweSeAk', 'Lise', 'Wornham', '01021771203', '1974-03-22', 'Female', '8 Lindbergh Street', 'Staff Accountant II', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('bgatch2o@photobucket.com', 'Ho6jtez', 'Brandy', 'Gatch', '01005569042',  '2005-02-13','Male', null, null, 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('fread2p@dailymail.co.uk', 'iU4gE01', 'Florencia', 'Read', '01070281629', '1959-06-01', 'Female', '905 Harper Circle', 'Safety Technician II', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('kdincey2q@nytimes.com', '81BNEdDzP0', 'Kelley', 'Dincey', '01032222670',  '1993-12-01','Male', null, null, 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('mreynard2r@bbc.co.uk', '6qiKG6q9DP9K', 'Mavis', 'Reynard', '01087063417', '1942-08-03', 'Female', '79 Autumn Leaf Park', 'Registered Nurse', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('aheeps2s@geocities.com', 'JDPRdfEV', 'Ardelis', 'Heeps', '01059349117', '1953-06-21', 'Female', '513 Elka Avenue', 'Pharmacist', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('jheigl2t@imageshack.us', 'RrZx2piX', 'Janeen', 'Heigl', '01029163126',  '1964-12-22','Male', null, null, 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('rmatkovic2u@google.com.hk', 'hiqcdXj', 'Rahel', 'Matkovic', '01027381198', '1942-12-06', 'Female', '544 Algoma Lane', 'Payment Adjustment Coordinator', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('lhellewell2v@tamu.edu', 'KmnFzsHhPHe', 'Larine', 'Hellewell', '01072655193', '1937-02-12', 'Female', '40378 Granby Court', 'Geologist III', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('mlongley2w@blogtalkradio.com', 'sfQWEPz1', 'Malchy', 'Longley', '01047655004', '2013-09-02', 'Male', '011 Delladonna Pass', 'Product Engineer', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('cjoannic2x@loc.gov', 'CdKH6tNr0', 'Cele', 'Joannic', '01016441276', '1992-01-13', 'Female', '2 Eagle Crest Way', 'Help Desk Operator', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('kdanahar2y@taobao.com', 'QMhO4XTV2', 'Kyla', 'Danahar', '01082178449', '1937-08-21', 'Female', '2910 Lillian Drive', 'Senior Editor', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('iarnauduc2z@intel.com', 'WyCD6u', 'Iolande', 'Arnauduc', '01088667163', '2019-07-31', 'Female', '0 Hudson Lane', 'Executive Secretary', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('jlouis30@soup.io', 'cC5azsM', 'Jerry', 'Louis', '01085202358', '2018-09-02', 'Male', '74825 Corscot Terrace', 'VP Marketing', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('bbridgland31@domainmarket.com', 'ta8iAaE', 'Byrle', 'Bridgland', '01000856957', '1994-03-08', 'Male', '1 Blaine Park', 'Staff Scientist', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('oceyssen32@microsoft.com', 'EkMt8ExwBG', 'Odella', 'Ceyssen', '01007468908', null, null, null, null, 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('djeschner33@wufoo.com', 'DUk5ef', 'Darrell', 'Jeschner', '01060575371', '1967-03-22', 'Male', '6 Crownhardt Junction', 'Executive Secretary', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('sventum34@etsy.com', 'MgVR0CRE7', 'Skipp', 'Ventum', '01071781991', '1996-02-01', 'Male', '41 Maryland Drive', 'Systems Administrator IV', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('ywant35@themeforest.net', 'EfmaHxwBJ', 'Ynes', 'Want', '01000147909', '2020-03-08', 'Female', '80 Gateway Street', 'Help Desk Operator', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('kedlington36@tinypic.com', '5f8V5oXVC', 'Katine', 'Edlington', '01009560860', '1984-01-02', 'Female', '2 Springs Park', 'Senior Financial Analyst', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('tbuey37@cocolog-nifty.com', '2QaDaq8t', 'Tracey', 'Buey', '01073476487',  '1969-08-25','Male', null, null, 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('dgowlett38@msu.edu', 'nswaSSj5U', 'Doralia', 'Gowlett', '01041108576', '1969-01-22', 'Female', '0729 Twin Pines Alley', 'Environmental Specialist', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('rlamble39@moonfruit.com', 'ysT2jplk', 'Rosabel', 'Lamble', '01034611975', '2019-06-01', 'Female', '313 David Street', 'Chief Design Engineer', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('ecerro3a@wikipedia.org', 'y6RF1vfG2wm', 'Esther', 'Cerro', '01079219842', '1980-11-22', 'Female', '1041 Karstens Circle', 'Business Systems Development Analyst', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('fglossop3b@uiuc.edu', 'ePrzWQzX6Bv', 'Felipa', 'Glossop', '01005760963', '1976-10-14', 'Female', '324 Rowland Circle', 'Human Resources Assistant I', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('mfoskew3c@arizona.edu', 'FeAZyGExE8', 'Mechelle', 'Foskew', '01084808762', '1941-08-08', 'Female', '29 Roth Point', 'Senior Financial Analyst', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('mscothron3d@newsvine.com', '0ckdiN', 'Mitzi', 'Scothron', '01060254694',  '1973-05-16','Male', null, null, 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('mstanlake3e@fastcompany.com', 'AaeYTByL', 'Maximilian', 'Stanlake', '01056735597', '2013-11-19', 'Male', '7319 Stephen Center', 'Database Administrator I', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('bspadari3f@cmu.edu', 'iGSl2VY', 'Buiron', 'Spadari', '01090174433', '1981-07-20', 'Male', '57996 Thackeray Circle', 'Nuclear Power Engineer', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('rduffitt3g@latimes.com', 'Q6fim7rzv', 'Raddy', 'Duffitt', '01089597518', '2005-02-24', 'Male', '2087 Morning Way', 'Senior Cost Accountant', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('htraut3h@myspace.com', 'aVmL6q4ra', 'Hildegaard', 'Traut', '01098390711', '2010-06-29', 'Female', '96 Mccormick Lane', 'Financial Analyst', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('cairey3i@pbs.org', 'jno7qwE', 'Currie', 'Airey', '01034931355', '2008-08-23', 'Male', '22005 Northview Drive', 'Design Engineer', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('tkoschek3j@weibo.com', 'OkpLIY9TV', 'Tito', 'Koschek', '01055754450', '1965-12-07', 'Male', '47 Barnett Alley', 'Occupational Therapist', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('dtithecott3k@wiley.com', 'Rhh0qMyngE', 'Darren', 'Tithecott', '01054057436', '2009-07-20', 'Male', '8 Burning Wood Parkway', 'Speech Pathologist', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('sgolby3l@uiuc.edu', 'Qi9w7CX', 'Stephan', 'Golby', '01026916867', '1984-12-23', 'Male', '3 Banding Trail', 'Environmental Specialist', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('tpessel3m@vimeo.com', 'ELCyLA', 'Torre', 'Pessel', '01079919275', null, null, null, null, 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('gpengelley3n@prweb.com', '2cpVPo0Us', 'Giavani', 'Pengelley', '01077846403', '1960-09-15', 'Male', '9286 Onsgard Plaza', 'Analog Circuit Design manager', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('ggarling3o@telegraph.co.uk', 'fS75i7dX5', 'Genevra', 'Garling', '01067318020', '1962-10-24', 'Female', '77 Marcy Crossing', 'Registered Nurse', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('mcreeber3p@blog.com', 'QgBWUeCb9', 'Mia', 'Creeber', '01009197246', '1933-08-22', 'Female', '21132 Bunker Hill Junction', 'Structural Analysis Engineer', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('nbenwell3q@examiner.com', 'hxDD1f6q', 'Nikolia', 'Benwell', '01047729192', '1982-04-08', 'Female', '6301 Merrick Junction', 'Financial Advisor', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('mblunt3r@desdev.cn', 'alhN6NRy3kds', 'Maurita', 'Blunt', '01035444427', '1979-01-08', 'Female', null, null, 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('fhair3s@utexas.edu', 'Ft3hkx96qj', 'Fabian', 'Hair', '01008994195', '2005-01-09', 'Male', '34 Northfield Trail', 'Human Resources Manager', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('snouch3t@pen.io', '4G1AlmeIR', 'Stewart', 'Nouch', '01019984760', '1994-06-03', 'Male', '45 Prairieview Plaza', 'Junior Executive', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('ppresnail3u@tiny.cc', 'XCmeWa6Awi', 'Philis', 'Presnail', '01008317400', '1987-05-13', 'Female', '4 Myrtle Avenue', 'Quality Engineer', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('cbattill3v@pcworld.com', '8ysJdG', 'Charin', 'Battill', '01081445864', '1982-12-08', 'Female', null, null, 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('ajuste3w@cnn.com', '4kBa4Q', 'Anitra', 'Juste', '01080037370', '1970-12-03', 'Female', null, null, 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('ftrench3x@nasa.gov', 'nif2qN', 'Flore', 'Trench', '01042400996', null, null, null, null, 'Basic', true);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('ewilletts3y@archive.org', 'KM2WwrwrRhRe', 'Eleanora', 'Willetts', '01009560170', '1951-07-23', 'Female', '7 Talmadge Point', 'Internal Auditor', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('scowpertwait3z@dot.gov', 'qNnezm', 'Shaine', 'Cowpertwait', '01029648672', '1980-02-03', 'Female', '2 Dryden Place', 'Administrative Officer', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('wiacoboni40@deviantart.com', 'fEtJPNNcq', 'Weider', 'Iacoboni', '01080537610', '1977-11-05', 'Male', '19782 Sachtjen Avenue', 'Payment Adjustment Coordinator', 'Basic', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('ldawidowsky41@pagesperso-orange.fr', '19NS4Kr3mW', 'Lulu', 'Dawidowsky', '01095287413', '1975-02-14', 'Female', '87115 Fuller Avenue', 'Health Coach III', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('rblaxeland42@nifty.com', 'jDSD3bQp', 'Rosa', 'Blaxeland', '01025372530', '2011-08-02', 'Female', '6443 Arapahoe Pass', 'Tax Accountant', 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('llanchester43@dedecms.com', 'VglCV1c', 'Libbi', 'Lanchester', '01024462511', '1969-01-25', 'Female', '84 Eastlawn Street', 'Environmental Tech', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('gaxworthy44@51.la', 'zDiFCM6FBv', 'Gert', 'Axworthy', '01016577481', '1985-02-23', 'Female', null, null, 'Premium', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('hblazdell45@mit.edu', 'QYtwlP7', 'Helenelizabeth', 'Blazdell', '01002016203', '1981-10-19', 'Female', '35 Tennessee Hill', 'Marketing Assistant', 'Prime', false);
insert into ACCOUNT (User_id, Password, First_name, Last_name, Phone_number, Birthday, Sex, Address, Job, Membership_status, Is_admin) values ('wbbf@naver.com', 'h1kpyhNvV', 'Tabbie', 'Brellin', '01034448473',  '2003-11-04', 'Male', null, null, 'Prime', false);

--is_admin false도 적절히 섞을까.
--select membership_status, count(*) from account group by membership_status;
