create table EPISODE (
	Movie_id INT references MOVIE(Movie_id),
	Episode_number INT,
	Episode_title VARCHAR(50),
	runtime INT,
	PRIMARY KEY(Movie_id, Episode_number)
);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (4, 1, 'Synchronised attitude-oriented concept', 90);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (4, 2, 'Grass-roots intermediate monitoring', 90);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (4, 3, 'Fully-configurable contextually-based complexity', 56);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (4, 4, 'Streamlined disintermediate definition', 69);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (4, 5, 'Implemented demand-driven architecture', 76);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (4, 6, 'Universal clear-thinking artificial intelligence', 85);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (91, 1, 'Sharable dynamic paradigm', 100);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (91, 2, 'Seamless responsive Graphical User Interface', 65);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (91, 3, 'Up-sized real-time task-force', 80);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (91, 4, 'Re-contextualized web-enabled strategy', 90);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (91, 5, 'De-engineered 6th generation website', 69);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (91, 6, 'Managed 24/7 open architecture', 81);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (101, 1, 'Programmable modular definition', 95);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (101, 2, 'Cloned cohesive internet solution', 84);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (101, 3, 'Expanded didactic artificial intelligence', 70);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (101, 4, 'Phased hybrid collaboration', 54);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (101, 5, 'Future-proofed encompassing Graphic Interface', 90);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (101, 6, 'Configurable zero defect migration', 75);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (101, 7, 'Enhanced multi-state pricing structure', 69);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (101, 8, 'Diverse context-sensitive knowledge base', 84);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (101, 9, 'Networked client-server installation', 65);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (101, 10, 'Open-source mission-critical hub', 78);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (101, 11, 'Integrated tangible migration', 100);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (101, 12, 'Realigned 6th generation frame', 70);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (97, 1, 'Versatile stable local area network', 55);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (97, 2, 'Mandatory 4th generation moderator', 57);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (97, 3, 'Multi-tiered tangible policy', 67);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (97, 4, 'Seamless tertiary productivity', 74);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (97, 5, 'Operative clear-thinking local area network', 67);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (97, 6, 'Universal zero administration definition', 78);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (97, 7, 'Re-engineered methodical adapter', 80);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (128, 1, 'Open-architected 24/7 project', 70);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (128, 2, 'Right-sized 4th generation initiative', 96);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (128, 3, 'Proactive discrete intranet', 73);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (128, 4, 'Realigned national function', 100);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (128, 5, 'Inverse heuristic moratorium', 67);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (128, 6, 'Open-architected composite open architecture', 51);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (128, 7, 'Reverse-engineered interactive workforce', 50);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (128, 8, 'Phased incremental software', 72);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (128, 9, 'User-friendly multi-tasking approach', 59);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (128, 10, 'Fundamental 5th generation task-force', 69);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (132, 1, 'Optimized global process improvement', 79);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (132, 2, 'Balanced homogeneous focus group', 64);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (132, 3, 'Open-source client-driven hub', 94);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (132, 4, 'Public-key mobile frame', 51);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (132, 5, 'Fully-configurable transitional standardization', 90);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (132, 6, 'Triple-buffered well-modulated toolset', 61);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (133, 1, 'Reactive interactive application', 54);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (133, 2, 'Open-architected multi-state flexibility', 64);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (133, 3, 'Digitized value-added groupware', 77);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (133, 4, 'Realigned asymmetric throughput', 62);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (133, 5, 'User-centric cohesive ability', 88);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (133, 6, 'Mandatory leading edge collaboration', 80);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (133, 7, 'Exclusive user-facing internet solution', 63);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (133, 8, 'Configurable disintermediate adapter', 84);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (133, 9, 'Total hybrid website', 72);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (133, 10, 'Function-based coherent architecture', 69);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (135, 1, 'Stand-alone asymmetric artificial intelligence', 65);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (135, 2, 'Proactive disintermediate knowledge base', 50);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (135, 3, 'Exclusive contextually-based architecture', 51);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (135, 4, 'Organic holistic knowledge base', 89);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (135, 5, 'Grass-roots discrete collaboration', 92);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (135, 6, 'Fundamental well-modulated complexity', 76);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (135, 7, 'Extended asynchronous portal', 86);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (135, 8, 'Fundamental 5th generation challenge', 64);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (135, 9, 'Innovative bi-directional product', 70);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (135, 10, 'Cross-platform next generation neural-net', 73);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (135, 11, 'Innovative logistical core', 66);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (135, 12, 'Down-sized dynamic data-warehouse', 92);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (135, 13, 'User-friendly global conglomeration', 63);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (135, 14, 'Streamlined bi-directional model', 77);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (138, 1, 'Fully-configurable needs-based toolset', 76);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (138, 2, 'Open-source system-worthy workforce', 99);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (138, 3, 'Synchronised heuristic customer loyalty', 59);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (138, 4, 'Vision-oriented high-level matrix', 74);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (138, 5, 'Versatile bifurcated algorithm', 98);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (171, 1, 'Enhanced bi-directional initiative', 88);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (171, 2, 'Managed methodical process improvement', 98);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (171, 3, 'Enhanced neutral intranet', 61);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (171, 4, 'Programmable empowering workforce', 91);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (171, 5, 'Robust national internet solution', 90);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (171, 6, 'Ergonomic foreground adapter', 99);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (175, 1, 'Integrated empowering policy', 60);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (175, 2, 'Expanded directional circuit', 57);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (175, 3, 'Versatile content-based groupware', 63);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (175, 4, 'Multi-lateral empowering infrastructure', 55);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (175, 5, 'Proactive eco-centric algorithm', 86);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (175, 6, 'Cross-group incremental algorithm', 96);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (175, 7, 'Operative radical productivity', 84);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (177, 1, 'Robust user-facing help-desk', 88);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (177, 2, 'Upgradable multi-state collaboration', 83);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (177, 3, 'Multi-tiered neutral firmware', 73);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (177, 4, 'Profit-focused static monitoring', 57);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (177, 5, 'Streamlined leading edge neural-net', 96);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (177, 6, 'Front-line secondary concept', 96);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (185, 1, 'Future-proofed mission-critical intranet', 92);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (185, 2, 'Optional actuating portal', 56);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (185, 3, 'Quality-focused motivating encoding', 66);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (185, 4, 'Operative 24 hour application', 57);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (185, 5, 'Adaptive mobile system engine', 79);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (185, 6, 'Multi-layered even-keeled knowledge base', 89);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (185, 7, 'Customer-focused coherent open architecture', 53);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (185, 8, 'Mandatory encompassing interface', 55);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (185, 9, 'Implemented dynamic migration', 94);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (185, 10, 'Enhanced intangible open architecture', 79);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (185, 11, 'Pre-emptive maximized portal', 98);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (187, 1, 'Grass-roots reciprocal methodology', 72);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (187, 2, 'Automated bandwidth-monitored hub', 84);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (187, 3, 'Switchable bi-directional emulation', 94);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (187, 4, 'Monitored hybrid utilisation', 68);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (187, 5, 'Enhanced global productivity', 67);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (187, 6, 'Reverse-engineered clear-thinking encryption', 66);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (187, 7, 'Mandatory composite portal', 59);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (187, 8, 'Multi-channelled impactful standardization', 66);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (187, 9, 'Vision-oriented scalable encryption', 99);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (196, 1, 'Customizable static middleware', 50);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (196, 2, 'Ameliorated foreground neural-net', 50);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (196, 3, 'Business-focused systemic capacity', 93);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (196, 4, 'Persistent dedicated application', 66);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (196, 5, 'Intuitive contextually-based utilisation', 58);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (196, 6, 'Quality-focused discrete service-desk', 66);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (196, 7, 'Devolved responsive knowledge base', 54);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (196, 8, 'Total content-based adapter', 79);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (199, 1, 'Seamless high-level synergy', 52);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (199, 2, 'Vision-oriented asynchronous help-desk', 75);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (199, 3, 'Front-line client-server application', 75);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (199, 4, 'Implemented non-volatile methodology', 76);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (199, 5, 'Proactive stable matrix', 60);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (199, 6, 'Optimized non-volatile moratorium', 58);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (200, 1, 'Monitored national throughput', 72);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (200, 2, 'Visionary interactive challenge', 91);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (200, 3, 'Total transitional conglomeration', 77);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (200, 4, 'Operative secondary access', 80);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (200, 5, 'Balanced empowering workforce', 61);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (200, 6, 'Inverse zero administration time-frame', 77);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (203, 1, 'Up-sized tertiary access', 98);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (203, 2, 'Adaptive impactful info-mediaries', 71);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (203, 3, 'Front-line content-based utilisation', 70);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (203, 4, 'Cross-platform interactive synergy', 77);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (203, 5, 'Visionary 3rd generation analyzer', 59);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (204, 1, 'Multi-channelled regional standardization', 90);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (204, 2, 'Configurable didactic process improvement', 99);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (204, 3, 'User-friendly empowering array', 58);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (204, 4, 'Focused next generation hardware', 91);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (204, 5, 'Operative incremental customer loyalty', 71);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (205, 1, 'User-centric tertiary orchestration', 78);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (205, 2, 'Seamless logistical open architecture', 63);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (205, 3, 'Up-sized scalable groupware', 99);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (205, 4, 'Cross-group 5th generation utilisation', 52);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (205, 5, 'Versatile interactive leverage', 61);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (205, 6, 'Versatile mission-critical local area network', 66);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (206, 1, 'Quality-focused fresh-thinking knowledge base', 55);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (206, 2, 'Cloned systemic migration', 54);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (206, 3, 'Devolved tangible intranet', 51);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (206, 4, 'Progressive coherent extranet', 64);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (206, 5, 'Balanced needs-based installation', 66);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (206, 6, 'Expanded responsive application', 60);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (206, 7, 'Integrated uniform conglomeration', 66);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (207, 1, 'Monitored needs-based time-frame', 67);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (207, 2, 'Open-architected 24/7 matrix', 70);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (207, 3, 'Multi-channelled upward-trending help-desk', 63);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (207, 4, 'Face to face static capability', 67);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (207, 5, 'Function-based fault-tolerant attitude', 60);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (207, 6, 'Polarised asynchronous architecture', 52);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (218, 1, 'Optimized human-resource definition', 59);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (218, 2, 'Fully-configurable stable model', 57);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (218, 3, 'Centralized coherent infrastructure', 59);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (218, 4, 'Horizontal systematic local area network', 51);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (218, 5, 'Ergonomic needs-based intranet', 60);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (218, 6, 'User-centric fresh-thinking functionalities', 55);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (231, 1, 'Realigned responsive customer loyalty', 60);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (231, 2, 'Assimilated directional hub', 64);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (231, 3, 'Monitored empowering data-warehouse', 55);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (231, 4, 'Extended bifurcated utilisation', 57);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (231, 5, 'Diverse tertiary synergy', 56);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (231, 6, 'Progressive dynamic archive', 52);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (231, 7, 'Devolved systematic budgetary management', 62);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (231, 8, 'Decentralized incremental paradigm', 50);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (258, 1, 'Synergistic holistic capability', 65);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (258, 2, 'Realigned mobile parallelism', 69);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (258, 3, 'Compatible upward-trending matrices', 53);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (258, 4, 'Intuitive tangible forecast', 57);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (258, 5, 'Streamlined well-modulated challenge', 59);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (258, 6, 'De-engineered neutral groupware', 52);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (258, 7, 'Innovative explicit projection', 66);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (258, 8, 'Mandatory 5th generation approach', 69);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (258, 9, 'Monitored context-sensitive application', 69);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (258, 10, 'Enterprise-wide maximized adapter', 70);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (258, 11, 'Integrated multimedia project', 57);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (264, 1, 'Cross-platform dedicated strategy', 60);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (264, 2, 'Multi-layered high-level budgetary management', 58);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (264, 3, 'Optimized 24/7 standardization', 55);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (264, 4, 'Proactive maximized approach', 66);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (264, 5, 'De-engineered contextually-based knowledge base', 58);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (264, 6, 'Reverse-engineered even-keeled encoding', 64);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (264, 7, 'Stand-alone cohesive success', 63);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (264, 8, 'Multi-lateral asymmetric concept', 55);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (264, 9, 'Fully-configurable homogeneous emulation', 54);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (278, 1, 'Networked methodical system engine', 51);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (278, 2, 'Adaptive bi-directional array', 69);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (278, 3, 'Switchable multimedia function', 70);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (278, 4, 'Integrated 24/7 toolset', 64);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (278, 5, 'Balanced dedicated conglomeration', 58);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (278, 6, 'Innovative zero administration forecast', 61);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (284, 1, 'Open-source solution-oriented capacity', 62);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (284, 2, 'Visionary holistic matrices', 50);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (284, 3, 'Streamlined web-enabled software', 65);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (284, 4, 'Grass-roots client-driven extranet', 67);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (284, 5, 'Re-engineered optimizing pricing structure', 69);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (284, 6, 'Open-architected 24/7 benchmark', 70);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (284, 7, 'Secured uniform toolset', 61);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (284, 8, 'Self-enabling national hub', 54);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (292, 1, 'Innovative dedicated leverage', 65);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (292, 2, 'Team-oriented executive parallelism', 67);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (292, 3, 'Balanced systemic implementation', 70);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (292, 4, 'Reactive analyzing secured line', 56);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (292, 5, 'Public-key neutral archive', 55);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (297, 1, 'Streamlined systemic project', 60);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (297, 2, 'Cloned solution-oriented matrices', 70);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (297, 3, 'Self-enabling solution-oriented flexibility', 56);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (297, 4, 'Upgradable empowering hierarchy', 68);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (297, 5, 'Focused mobile approach', 62);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (297, 6, 'Expanded system-worthy Graphical User Interface', 60);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (297, 7, 'Self-enabling user-facing workforce', 59);
insert into EPISODE (Movie_id, Episode_number, Episode_title, runtime) values (297, 8, 'Down-sized didactic alliance', 60);
